
export const publications = [
    {
      title:'The mammalian purine salvage pathway as an exploitable route for cerebral bioenergetic support after brain injury', 
      // authors:["Philipp Gessner", "Jenni Lum", "Bruno G. Frenguelli"], 
      journal:"Neuropharmacology", 
      link:'https://www.sciencedirect.com/science/article/pii/S0028390822004294', 
      abstract:'Purine-based molecules play ancient, fundamental, and evolutionarily-conserved roles across life on Earth, ranging from DNA and RNA, to the universal energy currency, ATP. In mammals, the two primary routes for the synthesis of the adenine nucleotides ATP, ADP and AMP, and, as a consequence, the major bioactive metabolite adenosine, are the de novo purine biosynthesis (DNPB) pathway, and the purine salvage pathway (PSP). Of the two, the PSP dominates in both the mammalian brain and heart. This is because the PSP utilizes the breakdown products of ATP, occasioned by the high energy demands of these organs, to rapidly regenerate adenine nucleotides. This resynthesis route, while efficient and energetically favourable, leaves these organs vulnerable to loss of salvageable metabolites, with the potential for protracted depletion of the means to synthesize ATP, and the ability to deploy neuro- and cardioprotective adenosine. Having previously shown that hippocampal cellular ATP and adenosine release can be increased by supplying substrates for the PSP (d-ribose and adenine), we now explore the expression of DNPB and PSP enzymes in hippocampal neurons and astrocytes based on available transcriptomic data. We find that key enzymes of the PSP are expressed at higher levels than those in the DNPB pathway, and that PSP enzymes are expressed at higher levels in neurons than in astrocytes. These data reflect the importance of the PSP in the mammalian brain and imply that pharmacological targeting of the PSP may be particularly beneficial to neurons at times of metabolic stress.'
    },
    {
      title:'The mammalian purine salvage pathway as an exploitable route for cerebral bioenergetic support after brain injury', 
      // authors:["Philipp Gessner", "Jenni Lum", "Bruno G. Frenguelli"], 
      journal:"Neuropharmacology", 
      link:'https://www.sciencedirect.com/science/article/pii/S0028390822004294', 
      abstract:'Purine-based molecules play ancient, fundamental, and evolutionarily-conserved roles across life on Earth, ranging from DNA and RNA, to the universal energy currency, ATP. In mammals, the two primary routes for the synthesis of the adenine nucleotides ATP, ADP and AMP, and, as a consequence, the major bioactive metabolite adenosine, are the de novo purine biosynthesis (DNPB) pathway, and the purine salvage pathway (PSP). Of the two, the PSP dominates in both the mammalian brain and heart. This is because the PSP utilizes the breakdown products of ATP, occasioned by the high energy demands of these organs, to rapidly regenerate adenine nucleotides. This resynthesis route, while efficient and energetically favourable, leaves these organs vulnerable to loss of salvageable metabolites, with the potential for protracted depletion of the means to synthesize ATP, and the ability to deploy neuro- and cardioprotective adenosine. Having previously shown that hippocampal cellular ATP and adenosine release can be increased by supplying substrates for the PSP (d-ribose and adenine), we now explore the expression of DNPB and PSP enzymes in hippocampal neurons and astrocytes based on available transcriptomic data. We find that key enzymes of the PSP are expressed at higher levels than those in the DNPB pathway, and that PSP enzymes are expressed at higher levels in neurons than in astrocytes. These data reflect the importance of the PSP in the mammalian brain and imply that pharmacological targeting of the PSP may be particularly beneficial to neurons at times of metabolic stress.'
    },
    {
      title:'The mammalian purine salvage pathway as an exploitable route for cerebral bioenergetic support after brain injury', 
      // authors:["Philipp Gessner", "Jenni Lum", "Bruno G. Frenguelli"], 
      journal:"Neuropharmacology", 
      link:'https://www.sciencedirect.com/science/article/pii/S0028390822004294', 
      abstract:'Purine-based molecules play ancient, fundamental, and evolutionarily-conserved roles across life on Earth, ranging from DNA and RNA, to the universal energy currency, ATP. In mammals, the two primary routes for the synthesis of the adenine nucleotides ATP, ADP and AMP, and, as a consequence, the major bioactive metabolite adenosine, are the de novo purine biosynthesis (DNPB) pathway, and the purine salvage pathway (PSP). Of the two, the PSP dominates in both the mammalian brain and heart. This is because the PSP utilizes the breakdown products of ATP, occasioned by the high energy demands of these organs, to rapidly regenerate adenine nucleotides. This resynthesis route, while efficient and energetically favourable, leaves these organs vulnerable to loss of salvageable metabolites, with the potential for protracted depletion of the means to synthesize ATP, and the ability to deploy neuro- and cardioprotective adenosine. Having previously shown that hippocampal cellular ATP and adenosine release can be increased by supplying substrates for the PSP (d-ribose and adenine), we now explore the expression of DNPB and PSP enzymes in hippocampal neurons and astrocytes based on available transcriptomic data. We find that key enzymes of the PSP are expressed at higher levels than those in the DNPB pathway, and that PSP enzymes are expressed at higher levels in neurons than in astrocytes. These data reflect the importance of the PSP in the mammalian brain and imply that pharmacological targeting of the PSP may be particularly beneficial to neurons at times of metabolic stress.'
    },
    {
      title:'The mammalian purine salvage pathway as an exploitable route for cerebral bioenergetic support after brain injury', 
      // authors:["Philipp Gessner", "Jenni Lum", "Bruno G. Frenguelli"], 
      journal:"Neuropharmacology", 
      link:'https://www.sciencedirect.com/science/article/pii/S0028390822004294', 
      abstract:'Purine-based molecules play ancient, fundamental, and evolutionarily-conserved roles across life on Earth, ranging from DNA and RNA, to the universal energy currency, ATP. In mammals, the two primary routes for the synthesis of the adenine nucleotides ATP, ADP and AMP, and, as a consequence, the major bioactive metabolite adenosine, are the de novo purine biosynthesis (DNPB) pathway, and the purine salvage pathway (PSP). Of the two, the PSP dominates in both the mammalian brain and heart. This is because the PSP utilizes the breakdown products of ATP, occasioned by the high energy demands of these organs, to rapidly regenerate adenine nucleotides. This resynthesis route, while efficient and energetically favourable, leaves these organs vulnerable to loss of salvageable metabolites, with the potential for protracted depletion of the means to synthesize ATP, and the ability to deploy neuro- and cardioprotective adenosine. Having previously shown that hippocampal cellular ATP and adenosine release can be increased by supplying substrates for the PSP (d-ribose and adenine), we now explore the expression of DNPB and PSP enzymes in hippocampal neurons and astrocytes based on available transcriptomic data. We find that key enzymes of the PSP are expressed at higher levels than those in the DNPB pathway, and that PSP enzymes are expressed at higher levels in neurons than in astrocytes. These data reflect the importance of the PSP in the mammalian brain and imply that pharmacological targeting of the PSP may be particularly beneficial to neurons at times of metabolic stress.'
    },
    {
        title:'The mammalian purine salvage pathway as an exploitable route for cerebral bioenergetic support after brain injury', 
        // authors:["Philipp Gessner", "Jenni Lum", "Bruno G. Frenguelli"], 
        journal:"Neuropharmacology", 
        link:'https://www.sciencedirect.com/science/article/pii/S0028390822004294', 
        abstract:'Purine-based molecules play ancient, fundamental, and evolutionarily-conserved roles across life on Earth, ranging from DNA and RNA, to the universal energy currency, ATP. In mammals, the two primary routes for the synthesis of the adenine nucleotides ATP, ADP and AMP, and, as a consequence, the major bioactive metabolite adenosine, are the de novo purine biosynthesis (DNPB) pathway, and the purine salvage pathway (PSP). Of the two, the PSP dominates in both the mammalian brain and heart. This is because the PSP utilizes the breakdown products of ATP, occasioned by the high energy demands of these organs, to rapidly regenerate adenine nucleotides. This resynthesis route, while efficient and energetically favourable, leaves these organs vulnerable to loss of salvageable metabolites, with the potential for protracted depletion of the means to synthesize ATP, and the ability to deploy neuro- and cardioprotective adenosine. Having previously shown that hippocampal cellular ATP and adenosine release can be increased by supplying substrates for the PSP (d-ribose and adenine), we now explore the expression of DNPB and PSP enzymes in hippocampal neurons and astrocytes based on available transcriptomic data. We find that key enzymes of the PSP are expressed at higher levels than those in the DNPB pathway, and that PSP enzymes are expressed at higher levels in neurons than in astrocytes. These data reflect the importance of the PSP in the mammalian brain and imply that pharmacological targeting of the PSP may be particularly beneficial to neurons at times of metabolic stress.'
    },
    {
        title:'The mammalian purine salvage pathway as an exploitable route for cerebral bioenergetic support after brain injury', 
        // authors:["Philipp Gessner", "Jenni Lum", "Bruno G. Frenguelli"], 
        journal:"Neuropharmacology", 
        link:'https://www.sciencedirect.com/science/article/pii/S0028390822004294', 
        abstract:'Purine-based molecules play ancient, fundamental, and evolutionarily-conserved roles across life on Earth, ranging from DNA and RNA, to the universal energy currency, ATP. In mammals, the two primary routes for the synthesis of the adenine nucleotides ATP, ADP and AMP, and, as a consequence, the major bioactive metabolite adenosine, are the de novo purine biosynthesis (DNPB) pathway, and the purine salvage pathway (PSP). Of the two, the PSP dominates in both the mammalian brain and heart. This is because the PSP utilizes the breakdown products of ATP, occasioned by the high energy demands of these organs, to rapidly regenerate adenine nucleotides. This resynthesis route, while efficient and energetically favourable, leaves these organs vulnerable to loss of salvageable metabolites, with the potential for protracted depletion of the means to synthesize ATP, and the ability to deploy neuro- and cardioprotective adenosine. Having previously shown that hippocampal cellular ATP and adenosine release can be increased by supplying substrates for the PSP (d-ribose and adenine), we now explore the expression of DNPB and PSP enzymes in hippocampal neurons and astrocytes based on available transcriptomic data. We find that key enzymes of the PSP are expressed at higher levels than those in the DNPB pathway, and that PSP enzymes are expressed at higher levels in neurons than in astrocytes. These data reflect the importance of the PSP in the mammalian brain and imply that pharmacological targeting of the PSP may be particularly beneficial to neurons at times of metabolic stress.'
    }
  ];